[flags]
# Whether to group processes with the same name together by default.
group_processes = true
# Remove space in tables
hide_table_gap = true
# Show tree mode by default in the processes widget.
tree = true
# Show processes as their commands by default in the process widget.
process_command = true

# Layout - layouts follow a pattern like this:
# [[row]] represents a row in the application.
# [[row.child]] represents either a widget or a column.
# [[row.child.child]] represents a widget.

# All widgets must have the type value set to one of ["cpu", "mem", "proc", "net", "temp", "disk", "empty"].
# All layout components have a ratio value - if this is not set, then it defaults to 1.
# Widget Layout:
[[row]]
  ratio=60
  [[row.child]]
  type="cpu"
[[row]]
  ratio=40
  [[row.child]]
    ratio=2
    type="proc"
    default=true
    [[row.child]]
      ratio=1
      type="mem"
