call plug#begin()
Plug 'dylanaraps/wal'
call plug#end()

colorscheme wal
set nocompatible
filetype indent plugin on
syntax on
set hlsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
set autoindent
set nostartofline
set ruler
set confirm
set mouse=a
set cmdheight=2
set number
set shiftwidth=4
set softtabstop=4
