#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

ck-launch-session dbus-launch --sh-syntax --exit-with-session i3


if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi


picom -b --detect-client-opacity --blur-background &
