# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH="${PATH}:${HOME}/.local/bin:${HOME}/.cargo/bin:${HOME}/.scripts"
(cat ~/.cache/wal/sequences &)

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="gallifrey"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to automatically update without prompting.
DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

export EDITOR='vim'

# Set personal aliases

# Emerge Aliases
alias emerge-ask="sudo emerge --ask --quiet"
alias emerge-depclean="sudo emerge -av --depclean"
alias emerge-newuse="sudo emerge --update --newuse --deep --quiet @world"
alias emerge-changeduse="sudo emerge --update --changed-use --deep --quiet @world"
alias emerge-upgrade="sudo emerge -uDU --keep-going --with-bdeps=y @world"

# General Aliases
alias make-conf="sudo vim /etc/portage/make.conf"
alias ytop="ytop -amps"
alias sizeof="sudo du -shx"
alias build-progress="sudo watch -cn 5 genlop -ct"
alias zshrc="vim .zshrc"
alias rm="rm -rf"
